site_name: Domain API Documentation
site_url: https://dactacreative.github.io/domain-api
repo_url: https://github.com/DACTACreative/domain-api
theme:
  name: material
  palette:
    primary: blue
    accent: orange
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand

nav:
  - Home: index.md
  - Test Connection: test.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js

strict: false
